@Blueprints = new Mongo.Collection('blueprints')
@DocumentSchemas = new Mongo.Collection('document_schemas')
@Attributes = new Mongo.Collection('attributes')
@ScreenSchemas = new Mongo.Collection('screen_schemas')
@Views = new Mongo.Collection('views')
@Routines = new Mongo.Collection('routines')

@Applications = new Mongo.Collection('applications')
@Documents = new Mongo.Collection('documents')
@UserAccess = new Mongo.Collection('user_access')
